"use client";

import type { Metadata } from "next";
import "./globals.css";
import SessionProviderWrapper from "./sessionProvider";
import { usePathname } from "next/navigation";
import Navbar from "@/components/Navbar/navbar";
import Footer from "@/components/footer/footer";
import ProtectedRoute from "./ProtectedRoute";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hideNavbarPaths = [
    "/login",
    "/signup",
    "/dashboard",
    "/verifyemail",
    "/forgotpassword",
    "/resetpassword",
    "/dashboard/postJob",
    "/dashboard/applicationReviews",
    "/dashboard/adminProfile",
  ];
  const shouldhideNavbar = hideNavbarPaths.includes(pathname) || pathname.includes("not-found");

  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          {!shouldhideNavbar && <Navbar />}
          {children}
          {!shouldhideNavbar && <Footer />}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
